library:
  music_directory: 
  playlist_directory: 
player:
  restore_state: Yes
grid:
  order:
    field: 
    desc: No
  columns: ['Length', 'Title', 'Artist', 'Album', 'Year', 'Added', 'Played']
gtk:
  darktheme: false
