library:
  music_directory:
  playlist_directory:
player:
  restore_state: Yes
grid:
  order:
    field:
    desc: No
  columns: [ 'Title', 'Artist', 'Album','Length', 'Year', 'Added', 'Played', 'Genre']
gtk:
  darktheme: false
